//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFApp.PhoneBookServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneBook", Namespace="http://schemas.datacontract.org/2004/07/MyWcfService")]
    [System.SerializableAttribute()]
    public partial class PhoneBook : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneBookServiceReference.IServicePhoneBook")]
    public interface IServicePhoneBook {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/GetById", ReplyAction="http://tempuri.org/IServicePhoneBook/GetByIdResponse")]
        WCFApp.PhoneBookServiceReference.PhoneBook GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/GetById", ReplyAction="http://tempuri.org/IServicePhoneBook/GetByIdResponse")]
        System.Threading.Tasks.Task<WCFApp.PhoneBookServiceReference.PhoneBook> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/GetAll", ReplyAction="http://tempuri.org/IServicePhoneBook/GetAllResponse")]
        WCFApp.PhoneBookServiceReference.PhoneBook[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/GetAll", ReplyAction="http://tempuri.org/IServicePhoneBook/GetAllResponse")]
        System.Threading.Tasks.Task<WCFApp.PhoneBookServiceReference.PhoneBook[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/AddPhoneBook", ReplyAction="http://tempuri.org/IServicePhoneBook/AddPhoneBookResponse")]
        void AddPhoneBook(WCFApp.PhoneBookServiceReference.PhoneBook phoneBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/AddPhoneBook", ReplyAction="http://tempuri.org/IServicePhoneBook/AddPhoneBookResponse")]
        System.Threading.Tasks.Task AddPhoneBookAsync(WCFApp.PhoneBookServiceReference.PhoneBook phoneBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/UpdatePhoneBook", ReplyAction="http://tempuri.org/IServicePhoneBook/UpdatePhoneBookResponse")]
        void UpdatePhoneBook(WCFApp.PhoneBookServiceReference.PhoneBook phoneBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/UpdatePhoneBook", ReplyAction="http://tempuri.org/IServicePhoneBook/UpdatePhoneBookResponse")]
        System.Threading.Tasks.Task UpdatePhoneBookAsync(WCFApp.PhoneBookServiceReference.PhoneBook phoneBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/DelatePhoneBook", ReplyAction="http://tempuri.org/IServicePhoneBook/DelatePhoneBookResponse")]
        void DelatePhoneBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhoneBook/DelatePhoneBook", ReplyAction="http://tempuri.org/IServicePhoneBook/DelatePhoneBookResponse")]
        System.Threading.Tasks.Task DelatePhoneBookAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePhoneBookChannel : WCFApp.PhoneBookServiceReference.IServicePhoneBook, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePhoneBookClient : System.ServiceModel.ClientBase<WCFApp.PhoneBookServiceReference.IServicePhoneBook>, WCFApp.PhoneBookServiceReference.IServicePhoneBook {
        
        public ServicePhoneBookClient() {
        }
        
        public ServicePhoneBookClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePhoneBookClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePhoneBookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePhoneBookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFApp.PhoneBookServiceReference.PhoneBook GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<WCFApp.PhoneBookServiceReference.PhoneBook> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public WCFApp.PhoneBookServiceReference.PhoneBook[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WCFApp.PhoneBookServiceReference.PhoneBook[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void AddPhoneBook(WCFApp.PhoneBookServiceReference.PhoneBook phoneBook) {
            base.Channel.AddPhoneBook(phoneBook);
        }
        
        public System.Threading.Tasks.Task AddPhoneBookAsync(WCFApp.PhoneBookServiceReference.PhoneBook phoneBook) {
            return base.Channel.AddPhoneBookAsync(phoneBook);
        }
        
        public void UpdatePhoneBook(WCFApp.PhoneBookServiceReference.PhoneBook phoneBook) {
            base.Channel.UpdatePhoneBook(phoneBook);
        }
        
        public System.Threading.Tasks.Task UpdatePhoneBookAsync(WCFApp.PhoneBookServiceReference.PhoneBook phoneBook) {
            return base.Channel.UpdatePhoneBookAsync(phoneBook);
        }
        
        public void DelatePhoneBook(int id) {
            base.Channel.DelatePhoneBook(id);
        }
        
        public System.Threading.Tasks.Task DelatePhoneBookAsync(int id) {
            return base.Channel.DelatePhoneBookAsync(id);
        }
    }
}
